# Header
menu:
    主页: /
    所有文章: /archives
    丝茉茉: /categories/simomo/
    相册: /photos
# SubNav
subnav:
    github: "https://github.com/jarson7426"
    weibo: "http://weibo.com/u/2732624311"
    zhihu: "#"
    rss: /atom.xml
# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true
top: true
# 是否开启动画效果
animate: true
# 是否在新窗口打开链接
open_in_new: false
# Miscellaneous
google_analytics: ''
favicon: /favicon.ico
#你的头像url
avatar: /img.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: jarson7426
#是否开启云标签
tagcloud: true
#是否开启友情链接
#不开启――
friends: false
#开启――
#friends:
#  百度一下: http://www.baidu.com
#  淘宝商城: http://www.taobao.com
#是否开启“关于我”。
#不开启――
#aboutme: false
#开启――
aboutme: true